# Regression (Manual)

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'resume_score', 'lpa'])

In [ ]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [ ]:
def initialize_parameters(layer_dims): # Initialize weights and biases for each layer for our NN

    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range (1,L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters

In [ ]:
initialize_parameters([2,2,1]) # Our NN has 2 input and then 1 hidden layer with 2 neurons and then output layer with 1 neuron

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, W, b): # Compute the output from a neuron using previous layer value, weight and bias (We took linear as Activation function in all neurons)

    Z = np.dot(W.T, A_prev) + b # z = wt*x + b

    return Z

In [ ]:
def L_layer_forward(X, parameters): # Forward propogation

    A = X
    L = len(parameters) // 2 # No of layers in the neural network

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+": ", A_prev)
        #print("W"+str(l)+": ", Wl)
        #print("b"+str(l)+": ", bl)
        #print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l)+": ", A)
        #print("**"*20)

    return A, A_prev

Passing Student 1

In [ ]:
X = df[['cgpa','resume_score']].values[0].reshape(2,1) # Shape(no of features, no of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat, A1 = L_layer_forward(X, parameters)

In [ ]:
loss = (y - y_hat)**2
loss

array([[13.5424]])

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X): # Update the parameters using gradient descent using lr = 0.01

    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

Passing Student 2

In [ ]:
X = df[['cgpa','resume_score']].values[1].reshape(2,1) # Shape(no of features, no of training example)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)

In [ ]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

Passing Student 3

In [ ]:
X = df[['cgpa','resume_score']].values[2].reshape(2,1) # Shape(no of features, no of training example)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)

In [ ]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.12214053, 0.12946256],
        [0.12215748, 0.12949081]]),
 'b1': array([[0.00322519],
        [0.00322802]]),
 'W2': array([[0.14325344],
        [0.14357505]]),
 'b2': array([[0.15236016]])}

Passing student 4

In [ ]:
X = df[['cgpa','resume_score']].values[3].reshape(2,1) # Shape(no of features, no of training example)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)

In [ ]:
update_parameters(parameters, y, y_hat, A1, X)
parameters

{'W1': array([[0.12895013, 0.14580562],
        [0.12902536, 0.14597373]]),
 'b1': array([[0.00458711],
        [0.00460159]]),
 'W2': array([[0.160862  ],
        [0.16223863]]),
 'b2': array([[0.17070503]])}

Epoch Implementation

In [ ]:
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa','resume_score']].values[j].reshape(2,1) # Shape(no of features, no of training examples)
        y = df[['lpa']].values[j][0]

        # Parameter initialization

        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A1, X)

        Loss.append((y-y_hat)**2)

    print("Epoch - ", i+1," , Loss - ",np.array(Loss).mean())

parameters

Epoch -  1  , Loss -  25.321744156025517
Epoch -  2  , Loss -  18.320004165722047
Epoch -  3  , Loss -  9.473661050729628
Epoch -  4  , Loss -  3.2520938634031613
Epoch -  5  , Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# Regression (Keras)

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'resume_score', 'lpa'])

In [ ]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-0.75064296,  0.60958326],
        [-0.3428024 , -0.8849519 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.18695605],
        [-0.38772094]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 31.8140 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 33.8904
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31.2680 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 28.5688 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20.7404 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31.3595
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.8789
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.3389
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.9613 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.5959
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.9193
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.3883
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.9789
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27.7446
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21.4611
Epoch 16/75
4/4 

In [ ]:
model.get_weights()

[array([[0.37385365, 0.37385365],
        [0.36555287, 0.36555287]], dtype=float32),
 array([0.27239195, 0.27239195], dtype=float32),
 array([[0.37298],
        [0.37298]], dtype=float32),
 array([0.20466232], dtype=float32)]

# Classification

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.DataFrame([[8,8,1], [7,9,1], [6,10,0], [5,12,0]], columns=['cgpa', 'resume_score', 'placed'])

In [ ]:
df

cgpa  resume_score  placed
0     8             8       1
1     7             9       1
2     6            10       0
3     5            12       0

In [ ]:
def initialize_parameters(layer_dims): # Initialize weights and biases for each layer for our NN

    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range (1,L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters

In [ ]:
# Utility function
def sigmoid(Z):

    A = 1/(1+np.exp(-Z))

    return A

In [ ]:
def linear_forward(A_prev, W, b): # Compute the output from a neuron using previous layer value, weight and bias (We took Sigmoid as Activation function in all neurons)

    Z = np.dot(W.T, A_prev) + b # z = wt*x + b

    A = sigmoid(Z)

    return A

In [ ]:
def L_layer_forward(X, parameters): # Forward propogation

    A = X
    L = len(parameters) // 2 # No of layers in the neural network

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+": ", A_prev)
        #print("W"+str(l)+": ", Wl)
        #print("b"+str(l)+": ", bl)
        #print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l)+": ", A)
        #print("**"*20)

    return A, A_prev

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X): # Update the parameters using gradient descent using lr = 0.01

    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]-(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]-(1-A1[1][0])*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

Passing Student 1

In [ ]:
X = df[['cgpa','resume_score']].values[0].reshape(2,1) # Shape(no of features, no of training example)
y = df[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ', -y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913


{'W1': array([[ 0.10005146,  0.10005146],
        [-1.24381463, -1.24381463]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.10083997]])}

Epoch Implementation

In [ ]:
parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa','resume_score']].values[j].reshape(2,1) # Shape(no of features, no of training examples)
        y = df[['placed']].values[j][0]

        # Parameter initialization

        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters, y, y_hat, A1, X)

        Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

    print("Epoch - ", i+1," , Loss - ",np.array(Loss).mean())

parameters

Epoch -  1  , Loss -  0.6866413111648185
Epoch -  2  , Loss -  0.6944055478538105
Epoch -  3  , Loss -  0.6944055478538105
Epoch -  4  , Loss -  0.6944055478538105
Epoch -  5  , Loss -  0.6944055478538105
Epoch -  6  , Loss -  0.6944055478538105
Epoch -  7  , Loss -  0.6944055478538105
Epoch -  8  , Loss -  0.6944055478538105
Epoch -  9  , Loss -  0.6944055478538105
Epoch -  10  , Loss -  0.6944055478538105
Epoch -  11  , Loss -  0.6944055478538105
Epoch -  12  , Loss -  0.6944055478538105
Epoch -  13  , Loss -  0.6944055478538105
Epoch -  14  , Loss -  0.6944055478538105
Epoch -  15  , Loss -  0.6944055478538105
Epoch -  16  , Loss -  0.6944055478538105
Epoch -  17  , Loss -  0.6944055478538105
Epoch -  18  , Loss -  0.6944055478538105
Epoch -  19  , Loss -  0.6944055478538105
Epoch -  20  , Loss -  0.6944055478538105
Epoch -  21  , Loss -  0.6944055478538105
Epoch -  22  , Loss -  0.6944055478538105
Epoch -  23  , Loss -  0.6944055478538105
Epoch -  24  , Loss -  0.6944055478538105
E

{'W1': array([[ 1.00051470e-01,  1.00051472e-01],
        [-1.29324362e+03, -1.94324357e+03]]),
 'b1': array([[6.43386301e-06],
        [6.43386301e-06]]),
 'W2': array([[0.10038149],
        [0.10038149]]),
 'b2': array([[0.09985655]])}

In [ ]:
# The loss is not getting lesser then .69 this can be because - Less data, Bad data, Wrong Weight initialization, Wrong Optimizer

# Classification (Keras)

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.DataFrame([[8,8,1], [7,9,1], [6,10,0], [5,12,0]], columns=['cgpa', 'resume_score', 'placed'])

In [ ]:
df

cgpa  resume_score  placed
0     8             8       1
1     7             9       1
2     6            10       0
3     5            12       0

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 1.0073079 ,  1.1953002 ],
        [ 0.45997488, -0.9817114 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.12830615],
        [ 0.6717876 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.7089 
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6586
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6749
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7082
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7352
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6591
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6590
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6591
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6859
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7175
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7175 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6860
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6603
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6758 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7169 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━

In [ ]:
# Even keras is not able to give better results